sudo: required

services:
  - docker

before_install:
  - docker-compose -v

script:
  - docker-compose run app22
  - docker-compose run app13
notifications:
  slack: $SLACK_INTEGRATION_DOMAIN:$SLACK_INTEGRATION_KEY
