tests:
  build: .
  volumes:
    - .:/code
  working_dir: /code
  entrypoint: "./phpunit.sh"
  tty: true
  stdin_open: true
  links:
    - elasticsearch
  environment:
    EX_ES_HOST: elasticsearch
    EX_ES_PORT: 9200

elasticsearch:
  image: elasticsearch:1.3
  command: elasticsearch -Des.network.bind_host=0.0.0.0
  ports:
      - "9200:9200"
      - "9300:9300"
